### ISSUE TITLE
Opensource portal API query by githubID don't return AAD info 

### ISSUE THREAD

**Issue by ruowan** [microsoft/opensource-portal#113]
My service depends on the opensource portal. But today 2020-04-14, I found the opensource portal API doesn't return AAD info by query this API https://repos.opensource.microsoft.com/api/people/links/github/${githubLogin}.

I refer the link https://github.com/microsoft/opensource-portal/blob/develop/API.md. My access pattern is using the personal access token to query.

**Comment by jeffwilcox** [comment]
Do you believe this is a regression (was it working for you in the past)?

**Comment by ruowan** [comment]
Any update recently? Yesterday I query the API locally it returns AAD info, but now it doesn't. It blocks my service.

**Comment by jeffwilcox** [comment]
I will follow up with you offline. These APIs should not be used in production applications and no SLA is provided for the personal access token use case.

**Comment by jeffwilcox** [comment]
Good news, this was fixed at 2:43PM Redmond time. Thanks for the report. 🐞 

If an app needs to be onboarded as a more official user, we can discuss another time.
