### ISSUE TITLE
Publishing public org memberships to github profile is broken

### ISSUE THREAD

**Issue by wbsmolen** [microsoft/opensource-portal#123]
Following the steps [outlined here](https://repos.opensource.microsoft.com/Azure/membership), I consistently get an error: 
![image](https://user-images.githubusercontent.com/3998040/79903982-9e961800-83d9-11ea-945a-cb7cb1cfa42f.png)

**Comment by jeffwilcox** [comment]
Legit bug. To confirm you're using the legacy OAuth model and not modern app?

**Comment by wbsmolen** [comment]
I think so. I'm not familiar with a specific 'github modern app', pardon my ignorance. Accessing via edge chromium. I pulled this from the dev tools console: `GET https://repos.opensource.microsoft.com/signin/github/increased-scope 500 (Internal Server Error)
`

**Comment by jeffwilcox** [comment]
OK. Are you trying to just run the container, or are you able to run this with the debugger attached (i.e. using F5 in an environment like Visual Studio Code)?

GitHub App is the newer model - it uses a certificate file - and is installed and used a little differently... https://developer.github.com/apps/about-apps/

**Comment by wbsmolen** [comment]
Interesting, thanks for the links. 

This conversation is not in the context of any application I'm running -- so there may be a fundamental misunderstanding on my side. I saw the button in the OSS repos site that said my public membership is 'concealed' and thought clicking the button would simply light up the badge in my profile. 

Candidly, I'm still not sure why github's best-practice implementation in _this particular scenario_ is a selfhosted app to facilitate REST calls. But I do see that flowchart at the bottom of the doc...

**Comment by jeffwilcox** [comment]
Oh. Sorry... didn't realize you were looking for support on the actual deployment of this project inside Microsoft. :).

Will take a look into this.

**Comment by jeffwilcox** [comment]
@wbsmolen this fix is being deployed to production now. Mind testing this again and letting me know if it works OK for you?

If it isn't fixed, just reopen the issue.

**Comment by wbsmolen** [comment]
@jeffwilcox confirmed issue is resolved. thanks for your help! and I didn't realize the portal _itself_ was OSS. sorry for the lack of clarity originally. :)

**Comment by jeffwilcox** [comment]
Awesome. Yeah it's a bit of Inception here. open source to do open source.
