### ISSUE TITLE
Branch renaming isn't displaying conditionally

### ISSUE THREAD

**Issue by bnb** [microsoft/opensource-portal#153]
**Describe the bug**
Currently, if a repo is created with `main` rather than `master`, the branch renaming (image below) suggesting that the default branch be renamed to `main` still shows up. This may also occur once the action to rename is taken, I'm not sure.

**To Reproduce**
* Create a new repo with `main` as the default branch.
* Go to the portal and see that the suggestion is there.

**Expected behavior**
A clear and concise description of what you expected to happen:
* If `main` is already the default branch, don't suggest the default branch be changed to `main`.

**Screenshots**
![image](https://user-images.githubusercontent.com/502396/87977423-b5adda00-ca9c-11ea-8eb5-62c8d9207ff9.png)

**Comment by jeffwilcox** [comment]
Thanks @bnb ... mind pointing me at the repo you created or are looking at this in, just for me to check with your repo in prod vs a dev env.?

**Comment by bnb** [comment]
this is checking against microsoft/virtual-events 👍🏻

**Comment by jeffwilcox** [comment]
Thanks for the report. Deployed a new change to experience by using a new tab and only highlighting when the name is not the ideal.
