### ISSUE TITLE
Query cache issue

### ISSUE THREAD

**Issue by gianghoang912** [microsoft/opensource-portal#168]
**Describe the bug**
I tried to setup the project last few weeks and currently meeting an issue with empty list of repository.  Some additional information:

- List of teams and list of members are showed up without any problem.
- List of repository from path /repos and /orgs-name/repos are not available. Below is the image for the page /repos
- I tried to debug and seems like it's a problem with query cache. So in the reposPager.ts, I force the app to load information from GitHub API instead of from cache (i.e. set queryCache.supportsRepositories in line 35 and 41 to false), the repository lists can be displayed as normal.

**Expected behavior**
All repositories should display normally.

**Screenshots**
![empty-repo](https://user-images.githubusercontent.com/14963166/100750326-261f1d00-33e6-11eb-98c7-66d6a2c59501.PNG)

**Comment by vatsalyagoel** [comment]
Hi @gianghoang912 Can you confirm that you don't have the issue with this patch? #156 I had similar issues

**Comment by gianghoang912** [comment]
Hi @vatsalyagoel : Actually, I applied your fix at lib/caching/redis.ts for another problem (which is joining an organization). Thank you for that.
I did not apply the fix at lib/github/core.ts, since I'm not really sure about its purpose.

Are you currently facing a similar issue with the query cache?

Btw, merry Xmas and happy new year :D

**Comment by jeffwilcox** [comment]
Sorry folks, let me compare this with our internal fork.

What scale orgs are you hoping to manage (# of repos etc)?

We originally were trying to pull and cache more like a proxy, but query cache was added to the and be eventually consistent... and there could be issues in a net new setup without migration.

**Comment by gianghoang912** [comment]
Hi @jeffwilcox : In total, we have nearly 10 orgs and around 750 repos. Our main organization is containing nearly 300 repos and still expanding

**Comment by jeffwilcox** [comment]
@gianghoang912 sorry it's been a while; we merged a _ton_ of changes in today, any chance you have a semi-working environment to try again?

We've also changed the Postgres schemas some, I think we originally thought of trying to allow other data providers, but are prioritizing postgres; yet I worry we aren't entirely sure how to effectively help others keep up with the changes without adopting some overly complicated entity stuff...

**Comment by gianghoang912** [comment]
@jeffwilcox Thank you, the new version is running on our environment
