### ISSUE TITLE
Feature: Manual linking (of service users)

### ISSUE THREAD

**Issue by Shegox** [microsoft/opensource-portal#189]
**Is your feature request related to a problem? Please describe.**
We have the use case that we have service users, which we would like to attach with service user meta information (flagging as a service user or adding a contact email for the team behind the user). As our service users are not part of the active directory, users can't, in a self-service manner, join the service users to our GitHub organizations. Currently an owner needs to add them manually and then they are showing up as "unlinked" in the portal. 

**Describe the solution you'd like**
My proposal would be to allow the current link editor (`/organization/whois/github/$github_name`) to be used to create links as well. This would allow portal sudors to manually create links for service accounts and thus ensures that all accounts in an organization have metadata attached. Additionally it would even allow that someone can create a link for a normal user if they are not able (e.g. external collaborator) to create it. 

**Describe alternatives you've considered**
Currently I don't have an alternative for that, but I opened this issue so we can discuss it, if that makes sense and what details may be required (e.g. feature flagging)

**Additional context**
Here already a pull request with the very bare bone implementation of "manual linking": #190

**Comment by jeffwilcox** [comment]
Merged. Note, @Shegox I placed it behind a feature flag for now, how that's ok - set env `FEATURE_FLAG_ALLOW_ADMIN_MANUAL_LINKING` to `1`.

**Comment by Shegox** [comment]
sounds great, thanks a lot @jeffwilcox 👍
