### ISSUE TITLE
It would be useful to add Dockerhub Info

### ISSUE THREAD

**Issue by brycem** [Microsoft/opensource-portal#25]
Under the "use" or "release" links in the nav header, it'd be helpful to have a link to getting started with releasing Dockerhub images through the Microsoft organization (https://hub.docker.com/r/microsoft/)

**Comment by jeffwilcox** [comment]
Thanks Bryce. I don't actually have much information about that process, any chance you know more? Feel free to share that info internally to jwilcox.

**Comment by msftgits** [comment]
@brycem Bryce, just reaching out again - any idea if such a resource on the docker hub side is already available?

Internally the resources pages are located here, if you'd like to submit a pull request: https://github.com/Microsoft/ospo-opensource/tree/develop/views/resources

**Comment by brycem** [comment]
Sorry for the delay - I've just emailed you the response I got to an internal docker DL query on the same topic.

**Comment by jeffwilcox** [comment]
Closing per internal thread
