### ISSUE TITLE
Please document the proper value for GITHUB_CALLBACK_URL

### ISSUE THREAD

**Issue by RobCannon** [Microsoft/opensource-portal#26]
I looked through the code, and it looks like it should be something like:

http://mysite.mydomain.com/auth/github/callback

But, that returns a '301 Moved Permanently' status code and my deployment is unable to authenticate with GitHub.

**Comment by RobCannon** [comment]
I see that this needs to be an https url.  Still not authorizing, but I am closing this issue for now.

**Comment by jeffwilcox** [comment]
Hey @RobCannon, thanks for opening/reporting; happy to try and help investigate issues. It might be good for us to sync over e-mail: we actually have a large swatch of updates that are not yet open source that need to be made public, and it might make your adoption of this project easier. My e-mail is jwilcox at microsoft.com...
