### ISSUE TITLE
Unable to authenticate with GitHub

### ISSUE THREAD

**Issue by RobCannon** [Microsoft/opensource-portal#27]
I think the GitHub configuration for my deployment is all correct.  The app redirects me to GitHub and I authorize the login.  Then the app gets into this redirection loop until GitHub invalidates my login due to too many redirections. 

It think the core issue is that that after GitHub has redirected back to the portal, it doesn't recognize that I am authenticated and starts the process over again.  Here is the response from the auth/github/callback as well as the root page.

HTTP/1.1 302 Found
Content-Length: 46
Content-Type: text/html; charset=utf-8
Location: /
Vary: Accept, Accept-Encoding
Server: Microsoft-IIS/8.0
Set-Cookie: sid=s%3ASr5Uvzu3hXwYlLS2u02Z4Q0VvmXqcsO-.Vi0vtu1q2tviNf9yWPhzYkwt0yrI3dL5m7z%2B7iRkoSM; Path=/; Expires=Sun, 14 May 2017 13:23:42 GMT; HttpOnly
X-Powered-By: Express
X-Powered-By: ASP.NET
Date: Sun, 07 May 2017 13:23:41 GMT

HTTP/1.1 302 Found
Content-Length: 68
Content-Type: text/html; charset=utf-8
Location: /auth/github
Vary: Accept, Accept-Encoding
Server: Microsoft-IIS/8.0
Set-Cookie: sid=s%3ASr5Uvzu3hXwYlLS2u02Z4Q0VvmXqcsO-.Vi0vtu1q2tviNf9yWPhzYkwt0yrI3dL5m7z%2B7iRkoSM; Path=/; Expires=Sun, 14 May 2017 13:23:42 GMT; HttpOnly
X-Powered-By: Express
X-Powered-By: ASP.NET
Date: Sun, 07 May 2017 13:23:41 GMT

**Comment by jeffwilcox** [comment]
Do you know if you have sessions working properly? While you have the session ID being shared here, if it isn't backed by Redis or another store, you'll likely get an infinite loop trying to auth, as the session information is never actually stored behind the scenes.

**Comment by jeffwilcox** [comment]
Looping back to see whether the auth part is fixed now with the newer bits, whether I should close this issue or not.

**Comment by RobCannon** [comment]
Yes.  Once I figure how the rest of the settings should be set, I will create a PR with some documentation.
