### ISSUE TITLE
Automate "pinning" awesome repositories for organizations

### ISSUE THREAD

**Issue by jeffwilcox** [microsoft/opensource-portal#48]
It would be great to be able to have an algorithm find new and interesting repositories in orgs and automatically pin up to 6 of those repos to the org page on GitHub.com.

This is blocked. At this time GitHub's API does not support pinning via an API call.

**Comment by nschonni** [comment]
Could also leverage the data about what repos the org owner has pinned themselves https://developer.github.com/v4/object/organization/ `pinnedRepositories`

**Comment by jeffwilcox** [comment]
Closing as something outside the scope of current investments of the past year.
