### ISSUE TITLE
Missing config/containers.json

### ISSUE THREAD

**Issue by RobCannon** [Microsoft/opensource-portal#72]
I think the file containers.json in the config directory is missing from the repository.  I think it should contain at least this, but it probably needs something for the definition of healthCheck and deployment but I am not sure how they should be defined and how they should be used.

{
  "docker": "env://IS_DOCKER?trueIf=1"
}

**Comment by jeffwilcox** [comment]
Interesting... we don't have a `containers.json` on our end... is there an exception/stack trace you can share?

**Comment by RobCannon** [comment]
The following code will fail, from middleware/passport-config.js on line 84.  The config.containers element is undefined, unless that file is present.

```
 let aadStrategy = new OIDCStrategy({
    redirectUrl: config.activeDirectory.redirectUrl,
    allowHttpForRedirectUrl: config.containers.docker || config.webServer.allowHttp,
    realm: config.activeDirectory.tenantId,
    clientID: config.activeDirectory.clientId,
    clientSecret: config.activeDirectory.clientSecret,
    oidcIssuer: config.activeDirectory.issuer,
    identityMetadata: 'https://login.microsoftonline.com/' + config.activeDirectory.tenantId + '/.well-known/openid-configuration',
    responseType: 'id_token code',
    responseMode: 'form_post',
    validateIssuer: true,
  }, activeDirectorySubset);

```

Further, I see where that is used to make HTTP allowable, which is useful since I making this work from a container where HTTPS termination will take place on the load balancer (code from middleware/index.js).

```
  if (!initializationError) {
    if (!web) {
      /* No web routes */
    } else if (config.containers && config.containers.deployment) {
      console.log('Container deployment: HTTP: listening, HSTS: on');
      app.use(require('./hsts'));
    } else if (config.containers && config.containers.docker) {
      console.log('Docker image: HTTP: listening, HSTS: off');
    } else if (config.webServer.allowHttp) {
      console.warn('WARNING: Development mode (DEBUG_ALLOW_HTTP): HTTP: listening, HSTS: off');
    } else {
      app.use(require('./sslify'));
      app.use(require('./hsts'));
    }
```

**Comment by jeffwilcox** [comment]
Found the files; they were added in a refactor for Docker support internally in the past.

https://github.com/Microsoft/opensource-portal/pull/75

This PR contains the file/s if you need access now.
