### ISSUE TITLE
What should initialize req.oss in index-linked.js

### ISSUE THREAD

**Issue by RobCannon** [Microsoft/opensource-portal#73]
After linking my accounts, when the app gets to line 29 of index-linked.js, the valued of req.oss is not defined and the app errors out because it is trying to access req.oss.entities.link.

What should be providing the value of req.oss?

**Comment by RobCannon** [comment]
Some more context.  This happens when accessing routes like /people or /repos.

I think I found the code that is setting the values for entities and entities.link in lib/config.js on line 119 in this block of code:

```
OpenSourceUserContext.prototype.setPropertiesFromLink = function (link, callback) {
  this.usernames.github = link.ghu;
  this.id.github = link.ghid.toString();
  this.id.aad = link.aadoid;
  this.usernames.azure = link.aadupn;
  this.entities.link = link;
  this.displayNames.azure = link.aadname;
  this.avatars.github = link.ghavatar;
  this.tokens.github = link.githubToken;
  this.tokens.githubIncreasedScope = link.githubTokenIncreasedScope;
  var modernUser = this.modernUser();
  if (!modernUser && this.id.github) {
    modernUser = this.createModernUser(this.id.github, this.usernames.github);
  }
  modernUser.link = link;
  callback(null, this);
};
```

When I step through with a debugger, I see that the code in setPropertiesFromLink  is executed.  But when the code later gets to this block from routes/index-linked.js, the value of oss is undefined.  I am not able to find where that value is initialized.

```
router.use(function (req, res, next) {
  const config = req.app.settings.runtimeConfig;
  const link = req.oss.entities.link;
  if (link && link.ghid) {
    next();
```

Am I missing some configuration value that causes this to get linked?

**Comment by jeffwilcox** [comment]
At this point @RobCannon are you using the `develop` branch as-is?

**Comment by RobCannon** [comment]
Other than adding the missing .json file from the config directory, yes.  But I think I found the issue.  My change has fixed this but I am still testing.  Expect a PR soon.
