### ISSUE TITLE
No results for multiple tags in search query

### ISSUE THREAD

**Issue by khan0604** [Microsoft/opensource-portal#82]
#### No results are found on multiple tags in search query for "Search Tags...." 

![image](https://user-images.githubusercontent.com/25402695/46503859-c77fa800-c849-11e8-9259-cad5d38b6446.png)

**Comment by James-N-M** [comment]
I noticed this to, I'm going to try and pick up this issue and get it done before hacktoberfest comes to and end ! ps. I've never worked on a node JS backend before wish me luck haha

**Comment by mykeels** [comment]
Any luck with this issue @James-N-M ?

**Comment by James-N-M** [comment]
@mykeels I couldn't manage to get the dev environment set up I think the documentation could use a refresh. I've never done any node js development

**Comment by jeffwilcox** [comment]
Thanks for reporting... the underlying tag search is actually a proprietary web site, opensource.microsoft.com, I'm not sure entirely why it is linked here, but I will open a bug with that team!

Jeff
