### ISSUE TITLE
"Error: Cannot find module 'documentdb'" when running "npm start"

### ISSUE THREAD

**Issue by mderriey** [microsoft/opensource-portal#84]
Hi,

We're running an older version of this app and would like to keep it up to date.
However, we're getting the following error message when running `npm start`: `Error: Cannot find module 'documentdb'`

Here are the steps to repro &mdash; I ran this in a VSTS agent Docker container because I don't have Python installed on my machine, but ignore those first few steps if you do have it

```
# Grab the Docker image
λ docker pull mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-16.04-standard

# Start a new container based on that image
λ docker run -it mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-16.04-standard /bin/bash

# Misc software versions
λ git --version
git version 2.20.1

λ node --version
v10.15.0

λ npm --version
6.6.0

# Clone the repo
λ git clone https://github.com/Microsoft/opensource-portal/
λ cd opensource-portal/

# Show master is up to date
λ git log -1
commit 09382587127fe53f5cbc4cfb832d2d128d82e292 (HEAD -> develop, origin/master, origin/develop, origin/HEAD)
Author: Jeff Wilcox <jwilcox@microsoft.com>
Date:   Wed May 2 11:32:31 2018 -0700

    Adding a project status update for May 2018 on the need to make some major changes

λ npm install
[wait for eternity]

λ npm run build
> opensource-portal@5.0.2 build /tmp/opensource-portal
> grunt

Running "copy:bootstrap" (copy) task
Created 3 directories, copied 16 files

Running "copy:typeaheadjs" (copy) task
Copied 6 files

Running "copy:typeaheadjsBootstrapPatch" (copy) task
Copied 1 file

Running "copy:octicons" (copy) task
Created 1 directory, copied 181 files

Running "copy:jquery" (copy) task
Copied 7 files

Running "copy:resources" (copy) task
Created 4 directories, copied 11 files

Running "copy:timeago" (copy) task
Copied 1 file

Running "copy:d3" (copy) task


Running "copy:c3" (copy) task
Copied 2 files

Running "build_less" task

Running "concat:dist" (concat) task

Running "less:dist" (less) task
>> 1 stylesheet created.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "compress:<%=builddir%>/bootstrap.css:<%=builddir%>/bootstrap.min.css" (compress) task
compressing file <%=builddir%>/bootstrap.css

Running "less:dist" (less) task
>> 1 stylesheet created.

Done.

λ npm start
> opensource-portal@5.0.2 start /tmp/opensource-portal
> node ./bin/www

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'documentdb'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/opensource-portal/middleware/initialize.js:14:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opensource-portal@5.0.2 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opensource-portal@5.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-03-15T02_41_06_859Z-debug.log
```

It seems the `documentdb` package is used here: https://github.com/Microsoft/opensource-portal/blob/09382587127fe53f5cbc4cfb832d2d128d82e292/middleware/initialize.js#L14, but it's not listed as a dependency in the `package.json` file.

We got through this error by running `npm install documentdb` but I guess it'd be needed in that repo as well? If so, happy to open a PR for that.

Let me know if you need any more information.
Thanks 👍

**Comment by jeffwilcox** [comment]
Yeah, we forked this project and unfortunately haven't done a fair job of keeping it up-to-date. I spent a chunk of Friday trying to get things ready for us to kill the private branch and get back to public development. It's hard since it's an app yet also a service and all that jazz. We can do better.

Mind sharing insight on the core functions you are using, so I can make sure you're up-to-date? Any modifications or are you using Azure table + AAD?

**Comment by mderriey** [comment]
Thanks for getting back to me @jeffwilcox, much appreciated 👋

I believe our use case of the app is pretty limited; 95% of it is we want to link work identities and GitHub identities together so that when someone leaves, a group of people who are members of a specific GitHub team can remove them from the GitHub org.

We didn't make any modifications, so it's based on AAD and Azure tables.

Any other info you might need, please let me know.
Cheers 🙇‍♂️

**Comment by mderriey** [comment]
One thing we also used is repo-based notifications for when people request to join a team or want to create a new repository.

While this is still mentioned in the code, the implementation is gone.

For details, we're looking at this file: https://github.com/Microsoft/opensource-portal/blob/15710bc7bd83e15d12dc4936a08b8867e87fdc62/routes/org/team/index.js#L218-L234

`createIssue` is not a function defined on the `Repository` class which definition is over at https://github.com/Microsoft/opensource-portal/blob/develop/business/repository.js

/cc @rs252 who was looking into this.

**Comment by rs252** [comment]
Hi Jeff,

When we were looking into the `createIssue` function we found that the file it was in had been removed (previously in `lib/repo.js`). It appears to have been removed in a **legacy code removal PR** (#32).  

Do you have any suggestions for how we can proceed?

Thank you!

**Comment by jeffwilcox** [comment]
Hey - yeah, so we removed (due to a chicken-and-egg problem) the use of GitHub issues for tracking approvals and workflow. Are you looking to just update older code, or to bring back that sort of capability?

The chicken-and-egg problem was: people had trouble getting started on GitHub; they would have to be members of the org; they would have to have notifications on; and even then, they'd have to know how to manage and review issues, etc.

Open to ideas.

I desperately want to move the approvals workflow into crisper ES6+ code, await/async, etc., to make it possible to debug. The original callback experience was... not good.

**Comment by mderriey** [comment]
Hey Jeff,

The GitHub issues-based notifications worked well for us, as it's built-in and doesn't require us to set up an email provider.

The problem you mentioned woul definitely not be one for us; it's not like we're getting a ton of notifications, and the members of the approval team know how it works and how to action.

@rs252 managed to dig the code that was removed and get it to work, so if you're interested in bringing it back as a way to handle notifications, we could see how the code has evolved from the `develop` branch we're working on and adapt it to the new structure if it has changed a lot.

No matter whether you're interested in bringing back this capability, we're still keen to try out the new version if you can manage to open-source it.

Cheers!

**Comment by rs252** [comment]
Hi Jeff,

Like @mderriey mentioned, we find the issue-based notifications really useful and it would be something our team would use. It would be great if you could bring back that functionality and give users the flexibility to choose whether they'd like to use it or not. Just an idea.

@preecington and I implemented the `createIssue` and `updateIssue` functionalities and would be keen on comparing it to the new structure if that's something you are open to. Our implementation enables maintainers to manage issues and appears to be a fairly straightforward process. That's on our end at least. 

We would definitely fork the new version if you open-source it as the capabilities are quite useful for us. Could you clarify the sorts of changes you intend to make to the current repo? Are you planning on converting all of the code to ES6+ and refactoring the structure of the project? How different do you intend the new version to be compared to the current repository? 

Thanks 😃

**Comment by jeffwilcox** [comment]
We ported to TypeScript and have been trying to move to await/async wherever possible to simplify the callback madness from before. I think that will actually make it a lot easier to restore capabilities such as the issue logic.

(I just realized I was missing _all_ of the notifications for this repo due to these messages being marked spam... feeling pretty bad here...)

**Comment by mderriey** [comment]
Hey Jeff,

Thanks for getting back to us and no problem at all.
It's not super urgent for us to move to the new version as the existing one fits our needs, it was more of a "let's not fall back too far" move.

We'll take another look at this and get back to you if we need.

Cheers
