### ISSUE TITLE
Where is configuration.js?

### ISSUE THREAD

**Issue by omerlh** [microsoft/opensource-portal#89]
I'm trying to figure out how to run this project, and both the readme and the post refer to `configuration.js`, but I couldn't find this file...

**Comment by jeffwilcox** [comment]
The short answer is... it's gone from a recent refactoring. Let me see if I can just get this syncing the daily changes. Sorry for the delay (summertime).

**Comment by jeffwilcox** [comment]
Closing, as this was replaced with the `config/` folder mapping environment vars.
